### ISSUE TITLE
Add hard wrap option

### ISSUE THREAD

**Issue by phil-opp** [slang800/tidy-markdown#16]
Long lines are ugly in diffs. But editing can be a pain, too. For example an enumeration with long items:

Without soft wrapping:
```
1. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
2. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
```

With soft wrapping:
```
1. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor  invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
2. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, 
no sea takimata sanctus est Lorem ipsum dolor sit amet. 
```

With formatted hard wrapping:
```
1. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
   tempor  invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
2. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, 
   no sea takimata sanctus est Lorem ipsum dolor sit amet. 
```

**Comment by slang800** [comment]
First off, I really don't want to add options in general. The idea is to output a canonical representation of a markdown document... A single "Right Way" to do it... So having extra configuration would defeat that purpose.

However, I _am_ tempted to use hard-wrapping for much the same reason it is used in source-code. But it causes a big issue in diffs. A single word added to the beginning of a paragraph will cause 3-4 lines after it to be changed due to rewrapping, inflating change stats by quite a bit.

Also, I'm not sure if I want to force people who don't have tidy-markdown (or a similar tool) to do wrapping manually. It seems like something that would raise the "barrier to entry" for editing my markdown docs, at least slightly.

Wrapping rules also introduce a certain amount of inconsistency due to non-wrappable elements like wide tables or links with long urls. Thus, a rule like "wrap everything at 80 chars" doesn't work. It needs to be pretty nuanced & couldn't be applied with a tool like editorconfig.

And finally, I find that very few people actually wrap their documents. I haven't done a formal survey of markdown, but from the ones I've checked it's rare. Even [your](https://raw.githubusercontent.com/phil-opp/nightly-libcore/1350556ba9f6dcdc202fff55f4ef2d22fea978c7/README.md) [own](https://raw.githubusercontent.com/phil-opp/rustos-experiment/8a4f63c3eb075943e578e6318f82cb6d161e65ce/README.md) [docs](https://raw.githubusercontent.com/phil-opp/blog_os/05f76f525ca7863d9f8736f3607b9fe684814d60/README.md) don't seem to be wrapped.

**Comment by phil-opp** [comment]
Yeah, I think I changed my mind on this. Thanks for explaining your reasoning!
