### ISSUE TITLE
Don't enforce H1 as the first header when front matter present

### ISSUE THREAD

**Issue by benbalter** [slang800/tidy-markdown#5]
A follow up to https://github.com/slang800/tidy-markdown/issues/4, while I agree (and really like) the idea of enforcing all documents to begin with an H1 (and then must go in order after that), often when writing a Jekyll post or page, there will be implicit H1s and H2s in the template (site and page title), and the first-level available to the post content should really be an H3.

Would it be possible to disable the H1 must be the top level header check if front-matter is present? At least in my mind, front matter denotes some sort of templating engine, for which the markdown file will be a partial, not an entire document.

On a related note, this library is great. It (and the Atom package) is exactly what I've been looking for for years and am going to be sending lots of folks this way (at GitHub we use markdown for *everything*). :smile:

**Comment by slang800** [comment]
Wonderful! I'm glad to hear that it's useful. :smile: 

As for dealing with pieces of a document that are stored as separate files - I agree that we need to support that. I'm not sure if we can assume that front-matter means it's a partial document, because I frequently have full documents that have front-matter, and partial documents that don't.

What I could do is make "first-header-correction" (FHC) into a setting - that way people can disable it if it's doing something bad. Or with [project-manager](https://atom.io/packages/project-manager), they could even disable on a per-project basis. That would get us pretty close. Plus, if atom's scoped settings ever supports a "contains front-matter" selector, people would immediately be able to start using rules like the one you described.

To get it even closer, I could try to split FHC into a separate command - that way, people who have automatic FHC disabled, could still run it whenever they want.

**Comment by benbalter** [comment]
> What I could do is make "first-header-correction" (FHC) into a setting

That sounds like the easiest, I'd suspect? I agree that front matter shouldn't be deterministic here.

**Comment by slang800** [comment]
(this is released in https://github.com/slang800/atom-tidy-markdown/releases/tag/v0.2.0)

**Comment by benbalter** [comment]
:sparkling_heart:  thanks again @slang800!

**Comment by slang800** [comment]
no prob! be sure to hmu if you have any other ideas for this project! :D
